name: WoW Build Tools
description: Build and release your World of Warcraft addons with ease.
branding:
  icon: zap
  color: blue

inputs:
  args:
    description: Arguments to pass to `wow-build-tools build`.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod

    - name: Build binary
      shell: bash
      run: |
        cd ${{ github.action_path }}
        go build -o ${{ github.workspace }}/wow-build-tools

    - name: Run wow-build-tools
      shell: bash
      run: |
        pwd
        ls -la .
        ./wow-build-tools build ${{ inputs.args }}
