name: Feature Request
description: Suggest a new feature or enhancement for wow-build-tools
title: "[Feat Req] "
labels: enhancement
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or enhancement for wow-build-tools. Please provide the following information to help us understand and evaluate your request.

  - type: input
    id: feature_name
    attributes:
      label: Feature Name
      description: Provide a brief name for the feature.
      placeholder: e.g., "Enhanced Logging"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature in detail. Include any relevant context or examples.
      placeholder: Provide a detailed description of the feature...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe the use case for the feature. How will it benefit users?
      placeholder: Describe the use case and benefits...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Provide any additional context or information that may be helpful in evaluating the feature request.
      placeholder: Add any other context about the feature request here...
