local addonName, addonTable = ...

-- @project-revision@
-- @project-hash@
-- @project-abbreviated-hash@
-- @project-author@
-- @project-date-iso@
-- @project-date-integer@
-- @project-timestamp@
-- @project-version@
-- @file-revision@
-- @file-hash@
-- @file-abbreviated-hash@
-- @file-author@
-- @file-date-iso@
-- @file-date-integer@
-- @file-timestamp@
-- @build-date@
-- @build-date-iso@
-- @build-date-integer@
-- @build-timestamp@
