name: PR Checks
on:
  pull_request:

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum

      - name: Go cache paths
        id: go-cache-paths
        run: |
          chmod -R 0755 $(go env GOCACHE)
          chmod -R 0755 $(go env GOMODCACHE)
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT

            # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      - name: Install Go dependencies
        run: go mod download

      - name: Run tests
        run: |
          echo "Creating temp directories..."
          mkdir -p ./.coverage
          # mkdir -p ./.test-results
          echo "Running tests..."
          go test -tags='' -v ./... -cover -coverpkg=./... -coverprofile="./.coverage/.cover.out"
          echo "Generating coverage report..."
          go tool cover -html="./.coverage/.cover.out" -o "./.coverage/report.html"

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ./.coverage
          include-hidden-files: true

      - name: Check release id
        id: check_release_id
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go run main.go github --slug=${{ github.repository }} --tag="v1.0.0-beta.2"
